name: "Assemble"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "rules/*.yaml"
      - "*.js"

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run assembler
        run: npm run assemble

      - uses: "marvinpinto/action-automatic-releases@d68defdd11f9dcc7f52f35c1b7c236ee7513bcc1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Link Sanitization Rules"
          files: |
            LICENSE
            sanitization_rules.yaml
